CREATE DATABASE petstore;
USE petstore;
CREATE TABLE category (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(100) NOT NULL,
creation_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE user (
id INT AUTO_INCREMENT PRIMARY KEY,
firstName VARCHAR(100) NOT NULL,
lastName VARCHAR(100) NOT NULL,
email VARCHAR(200) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
address TEXT,
mobile VARCHAR(15),
role ENUM('admin','customer','seller') DEFAULT 'customer',
creation_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE product (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(150) NOT NULL,
image VARCHAR(150),
description TEXT,
price DECIMAL(10,2) NOT NULL,
discount DECIMAL(5,2) DEFAULT 0.00,
stock INT NOT NULL,
cat_id INT NOT NULL,
created_by INT NOT NULL,
creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (cat_id) REFERENCES category(id)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (created_by) REFERENCES user(id)
ON DELETE CASCADE ON UPDATE CASCADE);
CREATE TABLE cart (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
product_id INT NOT NULL,
quantity INT NOT NULL,
added_date DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES user(id)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (product_id) REFERENCES product(id)
ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE orders (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
total_amount DECIMAL(10,2) NOT NULL,
order_status ENUM(
'Pending',
'Processing',
'Shipped',
'Delivered',
'Cancelled'
) DEFAULT 'Pending',
order_date DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES user(id)
ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE order_items (
id INT AUTO_INCREMENT PRIMARY KEY,
order_id INT NOT NULL,
product_id INT NOT NULL,
quantity INT NOT NULL,price DECIMAL(10,2) NOT NULL,
FOREIGN KEY (order_id) REFERENCES orders(id)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (product_id) REFERENCES product(id)
ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE wishlist (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
product_id INT NOT NULL,
added_date DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES user(id)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (product_id) REFERENCES product(id)
ON DELETE CASCADE ON UPDATE CASCADE,
UNIQUE (user_id, product_id)
);
INSERT INTO category (title) VALUES
('Pet Food'),
('Toys'),
('Cages'),
('Accessories'),
('Grooming');